# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-04 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=2000)),
                ('description', models.CharField(max_length=2000)),
                ('type', models.CharField(choices=[('B', 'Bool'), ('S', 'String'), ('N', 'Number')],
                                          default='S', max_length=10)),
            ],
        ),
    ]
